owner: EnglishBay
repo: status # The name of this repository

sites:
  - name: API
    url: https://api.englishbay.com.br
  - name: Frontend
    url: https://app.englishbay.com.br
  - name: Admin
    url: https://admin.englishbay.com.br
  - name: Blog
    url: https://englishbay.com.br/blog/
  - name: Home
    url: https://englishbay.com.br
  - name: LP Curso
    url: https://curso.englishbay.com.br

assignees: # Users to assign downtime issues (optional)
  - marcopandolfo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.englishbay.com.br
  logoUrl: https://media.englishbay.com.br/englishbay.jpg
  name: EnglishBay services status
  introTitle: Monitoring EnglishBay services
  introMessage: This is a status page which uses **real-time** data from our services
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/EnglishBay
    - title: EnglishBay
      href: https://englishbay.com.br

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
